### PR TITLE
UI improvements

### PR DESCRIPTION
**Pull request by tarekdj**
preview

### CODE REVIEW

**Comment by pborreli** [comment]
:+1: nice very good for a start
btw, @pierrejoye had the pleasure and surprise to meet @tarekdj in Symfony TN 2015 !

**Comment by pierrejoye** [comment]
Merci! :)

C'est possible mais pas en vert? Le vert ressemble trop a PEAR. Le logo est vert oui, mais peut-etre une couleur qui s'armonise bien avec le vert?

**Comment by tarekdj** [comment]
@pborreli le plaisir est pour moi :)
@pierrejoye couleurs complémentaires d'après ce site: http://paletton.com/#uid=72I0u0khZj69QsKeCnvmtfIr-aX

preview

**Comment by pierrejoye** [comment]
I like both :)

**Comment by tarekdj** [comment]
Vote ?

**Comment by pierrejoye** [comment]
I (and my half :) prefer the 2nd one after all.

But yes, a vote will make it!

**Comment by tarekdj** [comment]
:+1: for 2nd

**Comment by tarekdj** [comment]
@pborreli any choice ?

**Comment by JEDIBC** [comment]
I prefer the green one to the red one. Red is too violent and have an "error" connotaiton

**Comment by tarekdj** [comment]
Ok vote closed (quickly :) ) and PR updated

**Comment by pborreli** [comment]
2nd is better imo

**Comment by pierrejoye** [comment]
Go ahead to merge!

Thanks a lot! You rock :)

**Comment by tarekdj** [comment]
PR merged! Thank you all for the feedback

**Comment by jubianchi** [comment]
Awesome @tarekdj!

**Pull request merged**
