### PR TITLE
Draft frontend mockup

### PR DESCRIPTION
**Pull request by jubianchi**
I quickly built a frontend using [bootstrap](https://github.com/twbs/bootstrap):

capture-d ecran-2015-04-08-a-15 29 40

capture-d ecran-2015-04-08-a-15 29 36

capture-d ecran-2015-04-08-a-15 29 44

### CODE REVIEW

**Comment by pierrejoye** [comment]
Looks great, thanks! :)

Could you add the logo we now have?
It would be great if you provide the various templates as part of /templates? Especially index.html, account and co.

Thanks for the great work! :100:

**Comment by Hywan** [comment]
Where is the logo?

**Comment by Hywan** [comment]
:+1:

**Comment by jubianchi** [comment]
So what's left to do:
- [x] Revert CS fixes (will be done later, globally)
- [x] Put the templates in `/templates`
- [x] Split the templates
- [x] Add the logo to the home page
- [x] Add the logo in the header for all other pages

**Comment by jubianchi** [comment]
@pierrejoye I updated the PR, chck out the screenshots in the initial description ;)

ping @Hywan the logo (SVG) is here ;)

**Comment by pierrejoye** [comment]
Go ahead :) looks great!

Is it possible to use logos for bitbucket, github or other?

**Comment by jubianchi** [comment]
@pierrejoye Of course ;)

**Comment by Hywan** [comment]
:+1:

**Comment by pierrejoye** [comment]
is that good to merge now?

**Pull request merged**
